### ISSUE TITLE
Add GIF to readme

### ISSUE THREAD

**Issue by Islast** [WhitakerLab/BrainNetworksInPython#25]
We would like to turn [this video](https://youtu.be/ztm2knaLBFc) into a GIF and add it to the top right hand corner of the readme, in line with the first sentence.

**Comment by harshitjindal** [comment]
I can take this

**Comment by Islast** [comment]
:sparkles: Thanks @harshitjindal please go ahead

**Comment by harshitjindal** [comment]
Where do you want the gif to be placed? Next to which one?
- BrainNetworksInPython
- Welcome to the BrainNetworksInPython GitHub repository!✨

**Comment by Islast** [comment]
Closing  as #27 merged
