### ISSUE TITLE
Where to keep new visualisation scripts

### ISSUE THREAD

**Issue by Islast** [WhitakerLab/BrainNetworksInPython#3]
I've been making a lot of changes to the make_figure.py script so that it can run from the files output by network analysis. Would it be more organisationally proper to copy everything I need from make_figures over to visualisation commands and start clean in there? :blossom:

**Comment by KirstieJane** [comment]
YES! Please do exactly that! `visualisations.py` or something similar would be perfect 👍

**Comment by KirstieJane** [comment]
@Islast - if this answers your question you can go ahead and close the issue. If you think there are going to be more discussions on this (I know you're still working on the code) then you can totally leave it open 😄
