### ISSUE TITLE
Travis CI failing

### ISSUE THREAD

**Issue by Islast** [WhitakerLab/BrainNetworksInPython#32]
The current Travis build ([29](https://travis-ci.org/WhitakerLab/BrainNetworksInPython/builds/287489470)) is failing

**Comment by Islast** [comment]
There were a few people at Mozfest who had the `AttributeError: 'DegreeView' object has no attribute 'values'` error that interrupts builds of python 3.3 and later

**Comment by Islast** [comment]
This appears to be a networkx 1 to 2 migration issue. The [migration guide](https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html) seems to recommend using dict(G.degree()) to get the degrees as a dictionary. This should be backwards compatible with networkx 1

**Comment by KirstieJane** [comment]
Great find @Islast (and our fellow 🐛 finders at MozFest!)

**Comment by schae234** [comment]
Do you guys want to require networkx version 1.9 to fix the Travis tests first? Or are you planning on migrating to version 2.0 to fix things?

**Comment by Islast** [comment]
Good question @schae234 ! I think we will definitely want to migrate to networkx version 2.0 sometime. But for now I  we should probably change Travis to use version 1.9. If our Travis builds pass after that we can close this issue and create a new "networkx verison 2.0 compatability issue"

**Comment by schae234** [comment]
Hi @Islast , that sounds like a good plan! I have a fork thats [passing](https://travis-ci.org/schae234/BrainNetworksInPython) with python version 3.6, but the regression tests fail for other versions of python. I'm still looking into it! :+1:  

Do you know if there is a way to get the tests to be more verbose? I'm not familiar with the `unittest` package

**Comment by Islast** [comment]
Great job @schae23 ! I believe you use a -v to get "verbose" detail, as in:
```python
 python3 -m unittest discover -v -p '*_tests.py
```
in the .travis.yml

**Comment by Islast** [comment]
Some thoughts about why the non-3.6 tests might be failing. 
* The regression tests compare to files that were generated (using a fixed random seed) in python 3.6
* I notice that the corrmat tests don't fail - this is the only file that is created without using networkx
* The global and rich club measures both use the random seed, and these tests both fail, but the local measures do not use the random seed and they fail too

@schae234 if you feel like keeping going on this please do! If not, the work you've already done is extremely helpful :hibiscus:   
Feel free to PR whenever

**Comment by Islast** [comment]
Travis builds are now passing as of pull request #49
