### ISSUE TITLE
Considering the pros and cons of switching to igraph

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/BrainNetworksInPython#44]
Hi @Islast 

I came across these two repositories that I thought might be useful for speeding up the processing:

https://github.com/vtraag/python-igraph
https://github.com/vtraag/louvain-igraph

No action particularly required here, I just wanted to let you know that these two exist!

**Comment by Islast** [comment]
Closing because we have decided to carry on with networkx, mostly because it is already familiar to our contributors
