### ISSUE TITLE
networkx 2.0 compatibility

### ISSUE THREAD

**Issue by Islast** [WhitakerLab/BrainNetworksInPython#54]
I believ this is just a matter of putting `list(...)` around certain expressions which now return iterators rather than lists. 
Progress on this issue is taking place at PR #55

**Comment by KirstieJane** [comment]
CLOSING THIS ISSUE because it’s DONE!!! Wooooo! 

![](https://media1.giphy.com/media/3o751R1QccEmVqENmE/200w.gif)
