### ISSUE TITLE
object dtype issue in scripts/make_corr_matrices.py

### ISSUE THREAD

**Issue by zuxfoucault** [WhitakerLab/BrainNetworksInPython#56]
Just a note:
In the script scripts/make_corr_matrices.py, I have to modify the function `def create_corrmat(df, names, covars_list):` this line `M = df_res.loc[:, names].corr().values` into `M = df_res.loc[:, names].astype(float).corr().values`. In order to avoid `object` dtype error. 

Python 3.5.2 :: Anaconda 4.2.0 (64-bit)
numpy (1.11.1)
pandas (0.18.1)

**Comment by Islast** [comment]
Thank you Jessie, would you mind pulling from upstream to see if you still get the same error? 

(note:  you may not want to sync your master branch to upstream as this will overwrite your changes. You can create a new branch 
`git checkout -b upstream-copy`
 and reset it to a copy of the upstream master branch
`git reset --hard upstream/master`
if you get an ambiguous argument error you may not have th upstream set, in which case try
`git remote add upstream git@github.com:WhitakerLab/BrainNetworksInPython.git`
or if you don't have ssh access set up 
`git remote add upstream https://github.com/WhitakerLab/BrainNetworksInPython.git` )

**Comment by zuxfoucault** [comment]
Hi Islast,  thank you for your suggestions! I am not Jessie though, and followed the aforementioned instruction I still have the same issue.
![screen shot 2018-02-06 at 16 11 34](https://user-images.githubusercontent.com/3050531/35848392-f93600f0-0b58-11e8-85b0-09f5c0d8dc58.png)

**Comment by Islast** [comment]
:persevere: I'm so sorry! I don't know why I got confused.
Thanks for following the instructions,  I'll take another look at this

**Comment by Islast** [comment]
Okay, I like what you've done, I'm going to add this solution to the code.
Big thanks for alerting us to this problem :+1: :+1: :+1:

**Comment by KirstieJane** [comment]
Thank you @zuxfoucault for letting us know about the problem and thank you @Islast for fixing it!! I’m off to review #58 now!
