### ISSUE TITLE
manage dependencies

### ISSUE THREAD

**Issue by Islast** [WhitakerLab/BrainNetworksInPython#57]
consider adding dependency continuous integration
to deal with new releases of our dependencies
https://dependencyci.com/

**Comment by Islast** [comment]
I have played around with dependencyci.com and I haven't really got it-maybe we should try something else

**Comment by KirstieJane** [comment]
@Islast - do you want to close this issue, or leave it open incase someone wants to come along to help?

**Comment by Islast** [comment]
I'll close it, thanks
