### ISSUE TITLE
Check out new testing branch

### ISSUE THREAD

**Issue by Islast** [WhitakerLab/BrainNetworksInPython#8]
This is for @KirstieJane to remind her to look at the [new testing branch](https://github.com/Islast/BrainNetworksInPython/tree/testing). There's a lot of junk in there right now, firsttest.py and write_fixtures.py are the ones to check out!

**Comment by KirstieJane** [comment]
Awesome - thank you @Islast! 

I think the biggest challenge that I have at the moment is reading through the [firsttest.py](https://github.com/Islast/BrainNetworksInPython/blob/testing/firsttest.py) & [write_fixtures.py](https://github.com/Islast/BrainNetworksInPython/blob/testing/write_fixtures.py) files. Would you mind adding some comments to the functions to make it a little clearer.

I think, for example, that the actual running of the code in [firsttest.py](https://github.com/Islast/BrainNetworksInPython/blob/testing/firsttest.py) happens on [line 8](https://github.com/Islast/BrainNetworksInPython/blob/testing/firsttest.py#L8), is that right? and then `filecmp` compares files to check they're the same?

In the longer run, a little document explaining our (the project's) philosophy on testing would be really great. Something like 2-3 paragraphs and some links to useful resources and the specific tools you're using would be really helpful :smile:

Thank you again fro doing all this exploration!! I'm very excited about these tests!

**Comment by Islast** [comment]
Thanks! I had a feeling it was a bit obtuse. I'll try to make it clearer :sparkles:. And Yes a document explaining where we're at with testing is an excellent idea. Would the wiki be an appropriate place for that?
