### ISSUE TITLE
Broken link in README to Tutorial notebook

### ISSUE THREAD

**Issue by raamana** [WhitakerLab/BrainNetworksInPython#81]
Broken link in README to Tutorial notebook

Also it would be good to upload it to nbviewer and share the link directly - I think that would work on mobile also (which is where I tried to see this)..

**Comment by KirstieJane** [comment]
Thanks @raamana. I’ve fixed that now!

There’s actually a huge factor coming very soon (merging in less than 2 weeks) so if you’re looking at the code I’d recommend taking a look in the [`dev` branch](https://github.com/WhitakerLab/BrainNetworksInPython/tree/dev/) if you’re interested.....or swinging by in a couple of weeks 😱😬🤗

**Comment by KirstieJane** [comment]
Oh - and we’ll have the tutorials on binder in the future so shouldn’t need nbviewer (and you can see the notebook on GitHub if you go to desktop mode on mobile - as I’m sure you already know)
