### ISSUE TITLE
Broken links & broken badges in CONTRIBUTING guidelines

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/BrainNetworksInPython#9]
The [CONTRIBUTING](https://github.com/WhitakerLab/BrainNetworksInPython/blob/master/CONTRIBUTING.md) guidelines for this project use [shield.io](http://shields.io/) badges to make the labels look pretty. (Scroll down on http://shields.io to the *My Badge* section to see how they're made).

Some are broken though!

There are two errors as it stands in the [CONTRIBUTING](https://github.com/WhitakerLab/BrainNetworksInPython/blob/master/CONTRIBUTING.md) file:

1. The badge has a `-` in the name which is not working any more. The name of the link to the badge needs to be replaced with `--` where `-` is supposed to be rendered in the text of the badge.

    For example at the moment `https://img.shields.io/badge/-no-code-207de5.svg` does not render but `https://img.shields.io/badge/-no--code-207de5.svg` does show up as ![](https://img.shields.io/badge/-no--code-207de5.svg).

2. Some of the links are mis-typed.

    For example `[link_bugs]` doesn't actually exist, but there is a `[link_bug]` in the list at the end of the [CONTRIBUTING](https://github.com/WhitakerLab/BrainNetworksInPython/blob/master/CONTRIBUTING.md) file. Same with `[link_requests]` which should be `[link_request]`.

It would be great to have these fixed! Ping me if you have any questions @jlee124! 🌮 ✨

**Comment by KirstieJane** [comment]
Issue can be closed?

**Comment by faheel** [comment]
Yep, my bad! I forgot to refer it in my PR. I'll close it now as these errors have been fixed.

**Comment by KirstieJane** [comment]
No problem @faheel! Thank you so much for contributing :sparkles:
